apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-frontend
spec:
  selector:
    app: {{ include "my-app.name" . }}
    component: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  type: LoadBalancer
