replicaCount: 1

backend:
  image:
    repository: my-backend-image
  tag: 9e57a24
    tag: latest
  service:
    port: 5000

frontend:
  image:
    repository: my-frontend-image
  tag: 9e57a24
    tag: latest
  service:
    port: 80

ingress:
  enabled: false
  hostname: yourdomain.example.com
