name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract short commit SHA
        id: vars
        run: echo "SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build & Push Backend
        run: |
          docker build -t wly8/my-backend-image:${{ steps.vars.outputs.SHA_SHORT }} ./backend
          docker push wly8/my-backend-image:${{ steps.vars.outputs.SHA_SHORT }}
          docker tag wly8/my-backend-image:${{ steps.vars.outputs.SHA_SHORT }} wly8/my-backend-image:latest
          docker push wly8/my-backend-image:latest
      

      - name: Build & Push Frontend
        run: |
          docker build -t wly8/my-frontend-image:${{ steps.vars.outputs.SHA_SHORT }} ./frontend
          docker push wly8/my-frontend-image:${{ steps.vars.outputs.SHA_SHORT }}
          docker tag wly8/my-frontend-image:${{ steps.vars.outputs.SHA_SHORT }} wly8/my-frontend-image:latest
          docker push wly8/my-frontend-image:latest
      

      - name: Update Helm Chart with new Image Tag
        run: |
          sed -i "s|\(repository: my-backend-image\).*|\1\n  tag: ${{ steps.vars.outputs.SHA_SHORT }}|" helm/my-app/values.yaml
          sed -i "s|\(repository: my-frontend-image\).*|\1\n  tag: ${{ steps.vars.outputs.SHA_SHORT }}|" helm/my-app/values.yaml

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add helm/my-app/values.yaml
          git commit -m "chore: update image tags to ${{ steps.vars.outputs.SHA_SHORT }}"
          git push origin main
